[[angelus]]
=== Ángelus

V/ El Ángel del Señor anunció a María. +
R/ Y ella concibió por obra y gracia del Espíritu Santo.

*_Avemaría_*

V/ He aquí la excalva del Señor. +
R/ Hágase en mi según tu palabra.

*_Avemaría_*

V/ Y el Verbo se hizo. +
R/ Y habitó entre nosotros.

*_Avemaría_*

V/ Rogad por nosotros, Santa Madre de Dios. +
R/ Para que seamos dignos de alcanzar las promesas de Cristo.

*Oración* -- Os rogamos, Señor, que infundáis vuestra gracia en nuestras almas para que, habiendo conocido la Encarnación de vuestro Hijo Jesucristo por el Ángel que la anunció, seamos llevados a la gloria de la resurrección, por los méritos de su pasión y cruz santísim. Por el mismo Jesucristo nuestro Señor. Amén.

'''

_V/ Angelus Dómini nuntiávit Maríae._ +
_R/ Et concépit de Spíritu Sancto._

*_Avemaría_*

_V/ Ecce Amcilla Dómini._ +
_R/ Fiat mihi secúndum verbum tuum._

*_Avemaría_*

_V/ Et Verbum caro factum est._ +
_R/ Et habitávit in nobis._

*_Avemaría_*

_V/ Ora pro nobis, Sancta Dei Genetrix._ +
_R/ Ut digni efficiámur promissiónibus Christi. Amen._

*_Orémus_* -- _Grátiam tuam quáesumus. Dómine, méntibus nostris infúnde ut qui Angelo nuntiáte. Christi Filii tui incarnatiónem cognóvimus, per passiónem ejus et crucem ad resurrectiónis glóriam perducámur. Per eúmdem Christum Dóminum nostrum. Amen._
