[[angelus]]
=== Ángelus

V/ El Ángel del Señor anunció a María +
R/ Y ella concibió por obra y gracia del Espíritu Santo  

V/ He aquí la excalva del Señor +
R/ Hágase en mi según tu palabra  

V/ Y el Hijo de Dios se hizo hombre +
R/ Y habitó entre nosotros  

V/ Rogad por nosotros, Santa Madre de Dios +
R/ Para que seamos dignos de alcanzar las promesas de Cristo.  

*Oración* -- Os rogamos, Señor, que infundáis vuestra gracia en nuestras almas para que, habiendo conocido la Encarnación de vuestro Hijo Jesucristo por el Ángel que la anunció, seamos llevados a la gloria de la resurrección, por los méritos de su pasión y cruz santísim. Por el mismo Jesucristo nuestro Señor. Amén.

V/ _Angelus Dómini nuntiávit Maríae_ +
R/ _Et concépit de Spíritu Sancto_

V/ _Ecce Amcilla Dómini_
R/ _Fiat mihi secúndum verbum tuum_

V/ _Et Verbum caro factum est_ +
R/ _Et habitávit in nobis_

V/ _Ora pro nobis, Sancta Dei Genetrix_ +
R/ _Ut digni efficiámur promissiónibus Christi. Amen_

*_Orémus_* -- _Grátiam tuam quáesumus. Dómine, méntibus nostris infúnde ut qui Angelo nuntiáte. Christi Filii tui incarnatiónem cognóvimus, per passiónem ejus et crucem ad resurrectiónis glóriam perducámur. Per eúmdem Christum Dóminum nostrum. Amen._
