[[reginacoeli]]
=== Regina Cœli Lœtáre

Reina del Cielo, alegraos, aleluya. +
Porque Aquel que merecisteis llevar en vuestro seno, aleluya. +
Resucitó, como Él predijo, aleluya. +
Rogad por nosotros a Dios, aleluya. +
V/ Alegraos y regocijaos, Virgen María, aleluya +
R/ Porque resucitó verdaderamente el Señor, aleluya.  

*Oración* -- Oh Dios, que, por la resurreción de vuestro Hijo y Señor nuestro Jesucristo, os habéis dignado alegrar el mundo: concedednos por medio de su divina Madre, la Virgen Santísima, que merezcamos obtener los goces de la vida eterna. Por el mismo Cristo, Señor nuestro. Amén.

Regina caeli laetáre, allelúia. +
Quia quem meruisti portáre, allelúia. +
Resurréxit sicut dixit, allelúia. +
Ora pro nobis Deum, allelúia. +
V/ Gaudate el laetáre, Virgo María, allelúia. +
R/ Quia surréxit Dóminus vere, allelúia.  

*_Orémus_* -- _Deus, qui per resurrectiónem Filii tui Dómini nostri Jesu Christi, mundum laetificáre dignátus es: praesta, quáesumus, ut per ejus Genetricem Vírginem Maríam, perpétuae capiámus gáudia vitae. Per eúmdem Christum Dóminum nostrum. Amen._