== La señal de la Cruz

En el Nombre del Padre, y del Hijo, y del Espíritu Santo. Amén.

_In Nómine Pátris, et Filii, et Spíritus Sancti. Amen._

== Padrenuestro (Oración Dominical)

Padre Nuestro que estás en los cielos, santificado sea tu Nombre. Venga a nosotros tu Reino. Hágase tu voluntad, así en la tierra como en el cielo. El pan nuestro de cada día dánosle hoy. Y perdónamos nuestras deuda, así como nosotros perdonamos a nuestros deudores. Y no nos dejes caer en la tentación: mas líbranos del mal. Amén.

_Pater noster, qui es in cœlis, sanctifificétur nomen tuum. Advéniat regnum tuum. Fiat voluntas tua, sicut in cœlo et in terra. Panem nóstrum quotidiánum da nobis hódie. Et dimite nosbis debita nostra, sicut et nos dimittimus debitóribus nostris. Et ne nos indúcas in tentatiónem: sed libera nos a malo. Amen._

== Avemaría (Salutación Evangélica)

Dios de salve, María, llena eres de gracia, el Señor es contigo; dendita eres entre todas las mujeres, y bendito es el fruto de tu vientre, Jeeús. Santa María, Madre de Dios, ruega por nosotros pecadores, ahora u en el hora de nuestra muerte. Amén.

_Ave María, grátia plena, Dóminus tecum; benedicta tu in muliéribus, et benedictum fructus ventris tui, Jesus. Sancta Maria, Mater Dei, ora pro nobis peccatóribus, nunc et in hora mortis nostræ. Amen._

== Gloria Patri

V. Gloria al Padre, al Hijo, y al Espíritu Santo.  
R. Como era en el principio, ahora, y siempre, y por los siglos de los siglos. Amén.

_V. Gloria Patri, et Filio, et Spíritui Sancto._  
_R. Sicut erat in pcincípio et nunc, et semper et in sæcula sæculórum, Amen._

[[confiteor]]
== Confíteor

Yo pecador me confieso a Dios todopoderoso, a la bienaventurada siempre Virgen María, al bienaventurado San Miguel Arcángel, al bienaventurado San Juan Bautista, a los Santos Apóstoles Pedro y Pablo, y a todos los Santos, porque pequé gravemente de pensamiento, palabra y obra: por mi culpa, por mi culpa, por mi grandísima culpa. Por tanto, ruego a la bienaventurada siempre Virgen María, al bienaventurado San Miguel Arcángel, al bienaventurado San Juan Bautista, a los Santos Apóstoles Pedro y Pablo, y a todos los Santos, que roguéis por mi a Dios Nuestro Señor.  
R. El Señor omnipotente tenga piedad de nosotros y, perdonados nuestros pecados, nos lleve a la vida eterna. Amén.  
V. El Señor omnipotente y misericordioso nos conceda la indulgencia, la absolución y el perdón de nuestros pecados. Amén.

_Confíteor Deo omnipoténti, beátæ Maríæ semper Virigini, beáto Michaéli Archángelo, beáto Joánni Baptístæ, sanctis Apóstolis Petro et Paulo, ómníbus Sanctis et tibi, pater, quia peccávi nimis, cogitatióne, verbo et ópere, mea culpa, mea culpa, mea máxima culpa. Ideo precor beátam Maríam semper Virgínem, beátum Michaélem Archángelum, beátum Joánnem Bastístam, sanctis Apóstolos Petrum et Paolum, omnes Sanctos, et te, pater, oráre pro me ad Dóminum Deum nostrum.  
R. Misereátur nostri omnipotens Deus, et dimissis pecátis nostris, perdúcat nos ad vitam ætérnam. Amen.  
V. Indulgéntiam, absolutiónem, et remissiónem pecatórum nostrórum, tribuat nobis omnipotens et miséricors Dóminus. Amen._

== Credo Apostólico (Símbolo de los Apóstoles)

Creo en Dios, Padre todopoderoso. Creador del cielo y de la tierra. Y en Jesucristo, su único Hijo, Nuestro Señor, que fue concebido por obra y gracia del Espíritu Santo; nació de Santa María Vírgen; padeció bajo el poder de Poncio Pilato, fue crucificado, muerto y sepultado; descendió a los infiernos; al tercer día resucitó de entre los muertos; subió a los cielos, está sentado a la derecha de Dios Padre todopoderoso; desde allí ha de venir a juzgar a vivos y muertos. Creo en el Espíritu Santo, la Santa Iglesia Católica, la comunión de los Santos, el perdón de los pecados, la resurección de la carne y la vida eterna. Amén.

_Credo in Deum, Patrem omnipoténtem. Creatórem cœli et terræ. Et in Jesum CHristum, Filium ejus únicum, Dóminum nostrum; qui concéptus est de Spíritu Sancto; natus ex María Virgine; passus sub Póntio Pilato, crucifíxus, mortuus et sepúltus: descéndit ad inferos; tértia die resurréxit a mórtuis: ascéndit ad cœlos, sedet ad dexteram Dei Patris omnipoténtis; inde ventúrus est judicáre vivos et mórtuos. Credo in Spíritum Sanctum, sanctam Ecclésiam cathólicam, Sanctórum communiónem, remisiónem peccatórum, carnis resurrectiónem, vitam ætérnam. Amen._

<<gozosos, Misterios Gozosos>>
<<dolorosos, Misterios Dolorosas>>
<<gloriosos, Misterios Gloriosos>>
<<luminosos, Misterios Luminosos>>

include::./rosario/gozosos.adoc[]
include::./rosario/dolorosos.adoc[]
include::./rosario/gloriosos.adoc[]
include::./rosario/luminosos.adoc[]
