=== Confíteor

Yo pecador me confieso a Dios todopoderoso, a la bienaventurada siempre Virgen María, al bienaventurado San Miguel Arcángel, al bienaventurado San Juan Bautista, a los Santos Apóstoles Pedro y Pablo, a todos los Santos y a vos, Padre, que pequé mucho de pensamiento, palabra y obra: por mi culpa, por mi culpa, por mi grandísima culpa. +
Por tanto, ruego a la bienaventurada siempre Virgen María, al bienaventurado San Miguel Arcángel, al bienaventurado San Juan Bautista, a los Santos Apóstoles Pedro y Pablo, a todos los Santos, y a vos, Padre, que roguéis por mi a Dios Nuestro Señor. +
R/ El Señor omnipotente tenga piedad de nosotros y, perdonados nuestros pecados, nos lleve a la vida eterna. Amén. +
V/ El Señor omnipotente y misericordioso nos conceda la indulgencia, la absolución y el perdón de nuestros pecados. Amén.

_Confíteor Deo omnipoténti, beátæ Maríæ semper Virigini, beáto Michaéli Archángelo, beáto Joánni Baptístæ, sanctis Apóstolis Petro et Paulo, ómníbus Sanctis et tibi, pater, quia peccávi nimis, cogitatióne, verbo et ópere, mea culpa, mea culpa, mea máxima culpa. +
Ideo precor beátam Maríam semper Virgínem, beátum Michaélem Archángelum, beátum Joánnem Bastístam, sanctis Apóstolos Petrum et Paolum, omnes Sanctos, et te, pater, oráre pro me ad Dóminum Deum nostrum. +
R/ Misereátur nostri omnipotens Deus, et dimissis pecátis nostris, perdúcat nos ad vitam ætérnam. Amen. +
V/ Indulgéntiam, absolutiónem, et remissiónem pecatórum nostrórum, tribuat nobis omnipotens et miséricors Dóminus. Amen._

=== Acto de contrición

Señor mío Jesucristo, Dios y Hombre verdadero, Creador y Redentor mío: por ser vos quién sois, y porque os amo sobre todas las cosas, me pesa de todo corazón de haberos ofendido, propongo firmemente nunca más pecar, y apartarme de todas las ocasiones de ofenderos, confesarme, y cumplir la penitencia que me fuere impuesta; ofrézcoos mi vida, obras y trabajos en satisfacción de todos mis pecados; y confío en vuestra bondad y misericordia infinita me los perdonaréis por los merecimientos de vuestra preciosísima sangre, pasión y muerte, y me daréis gracia para enmendarme y para perseverar en vuestro santo servicio hasta el fin de mi vida. Amén.

=== Credo Apostólico (Símbolo de los Apóstoles)

Creo en Dios, Padre todopoderoso. Creador del cielo y de la tierra. Y en Jesucristo, su único Hijo, Nuestro Señor, que fue concebido por obra y gracia del Espíritu Santo; nació de Santa María Vírgen; padeció bajo el poder de Poncio Pilato, fue crucificado, muerto y sepultado; descendió a los infiernos; al tercer día resucitó de entre los muertos; subió a los cielos, está sentado a la derecha de Dios Padre todopoderoso; desde allí ha de venir a juzgar a vivos y muertos. Creo en el Espíritu Santo, la Santa Iglesia Católica, la comunión de los Santos, el perdón de los pecados, la resurección de la carne y la vida eterna. Amén.

_Credo in Deum, Patrem omnipoténtem. Creatórem cœli et terræ. Et in Jesum CHristum, Filium ejus únicum, Dóminum nostrum; qui concéptus est de Spíritu Sancto; natus ex María Virgine; passus sub Póntio Pilato, crucifíxus, mortuus et sepúltus: descéndit ad inferos; tértia die resurréxit a mórtuis: ascéndit ad cœlos, sedet ad dexteram Dei Patris omnipoténtis; inde ventúrus est judicáre vivos et mórtuos. Credo in Spíritum Sanctum, sanctam Ecclésiam cathólicam, Sanctórum communiónem, remisiónem peccatórum, carnis resurrectiónem, vitam ætérnam. Amen._

=== ¡Oh Jesús mío!

include::./rosario/ohjesus.adoc[attributes]

== Santo Rosario

=== Misterios Gozosos (Lunes y Jueves)

==== La Anunciación de la Santísima Virgen María

include::./rosario/gozosos/01-anunciacion-corta.adoc[attributes]

1 Paternoster, 10 Avemarías,  1 Gloria y ¡Oh Jesús mío!

==== La Visitación de Nuestra Señora 

include::./rosario/gozosos/02-visitacion-corta.adoc[attributes]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Natividad de Nuestro Señor Jesucristo

include::./rosario/gozosos/03-natividad-corta.adoc[attributes]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Presentación del Niño Jesús en el Templo

include::./rosario/gozosos/04-presentacion-corta.adoc[attributes]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Pérdida y Hallazgo del Niño Jesús en el Templo 

include::./rosario/gozosos/05-perdida-corta.adoc[attributes]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

=== Misterios Dolorosos (Martes y Viernes)

==== La Agonía de Nuestro Señor en el Huerto de los Olivos

include::./rosario/dolorosos/01-agonia-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La flagelación de Nuestro Señor Jesucristo

include::./rosario/dolorosos/02-flajelacion-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La coronación de espinas de Nuestro Señor Jesucristo {#espinas}

include::./rosario/dolorosos/03-espinas-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== Jesús con la Cruz a cuestas

include::./rosario/dolorosos/04-cruz-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Crucifixión y Muerte del Redentor

include::./rosario/dolorosos/05-muerte-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

=== Misterios Gloriosos (Miércoles, Sábados y Domingos)

==== La Resurección del Señor

include::./rosario/gloriosos/01-resurreccion-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Ascensión de Jesucristo a los cielos

include::./rosario/gloriosos/02-ascension-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Venida del Espíritu Santo sobre los Apóstoles

include::./rosario/gloriosos/03-pentecostes-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Asunción de Nuestra Señora a los cielos

include::./rosario/gloriosos/04-asuncion-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria y ¡Oh Jesús mío!

==== La Coronación de la Santísima Virgen María

include::./rosario/gloriosos/05-coronacion-corta.adoc[]

1 Paternoster, 10 Avemarías, 1 Gloria, ¡Oh Jesús mío!