[[rosario,Rosario]]
== Rosario Meditado{blank}footnote:[Los que lleven consigo el Rosario debidamente bedecido y lo besaren devotamente diciendo las palabras «Dios te salve, María, llena eres de gracia, el Señor es contigo, bendita Tú eres entre las mujeres, y bendito es el fruto de tu vientre, Jesús», su Santidad el Papa Pío XII concede perpetuamente 300 días de indulgencia una vez al día.]

'''

Por la señal de la santa Cruz. +
V/ Ave María, grátia plena. Dóminus tecum. +
R/ _Benedicta tu in muliéribus et benedictus fructus ventris tui, Jesus._ +
V/ Dómine, lábia mea apéries. +
R/ _Et os meum annuntiábit laudem tuam._ +
V/ Deus, in adjutórium meum inténde. +
R/ _Dómine, ad adjuvándum me festina._ +
V/ Glória Patri et Filio et Spiritui Sancto +
R/ _Sicut erat in principio et nunc et semper, et in sǽcula sæculórum. Amen. Allelúia._

María, Madre de gracia, Madre de piedad y misericordia; defiéndenos e nuestros enemigos, y ampáranos ahora y en la hora de nuestra muerta. Amén.

'''

<<confiteor, Confíteor>> +
<<actorContricion, Acto de contrición>>

'''

<<gozosos, Misterios Gozosos (Lunes y Jueves)>> +
<<dolorosos, Misterios Dolorosos (Martes y Viernes)>> +
<<gloriosos, Misterios Gloriosos (Domingos, Miércoles, Sábados)>> +
//<<luminosos, Misterios Luminosos (Jueves)>>

include::./rosario/gozosos.adoc[]
include::./rosario/dolorosos.adoc[]
include::./rosario/gloriosos.adoc[]
//include::./rosario/luminosos.adoc[]
include::./rosario/letanias.adoc[]

