[[natividadvirgen]]
=== Novena por la Natividad de la Santísima Virgen María

*Oración inicial*

¡Oh María santísima! elegida y destinada ab eterno por la augustísima Trinidad para Madre del unigénito Hijo del Padre, anunciada por los Profetas, esperada de los Patriarcas, y deseada de todas las gentes; sagrario y templo vivo del Espíritu Santo, sol sin mancha, porque fuisteis concebida sin pecado original, Señora del cielo y de la tierra, Reina de los Ángeles; nosotros humildemente postrados os veneramos, y nos alegramos de la solemne conmemoración anual de vuestro felicísimo Nacimiento; y de lo mas íntimo de nuestro corazón os suplicamos que os dignéis benigna venir a nacer espiritualmente en nuestras almas, para que cautivadas estas por vuestra amabilidad y dulzura, vivan siempre unidas a vuestro dulcísimo y amabilísimo Corazón.

_Pedir la gracia que deseo alcanzar de María en esta Novena_.

* *Primer día*: Ahora con nueve distintas salutaciones contemplaremos los nueve meses que estuvisteis encerrada en el seno materno; diciéndoos que oriunda de la Real prosapia de David, salisteis con grande honor a luz de las entrañas de santa Ana vuestra afortunadísima madre. _Avemaría_.

* *Segundo día*: Os saludamos, oh Niña celestial, paloma candidísima de pureza, que a despecho del infernal dragón fuisteis concebida sin pecado original. _Avemaría_.

* *Tercer día*: Os saludamos, oh Aurora brillantísisima, que como precursora del Sol de justicia, trajisteis la primera luz al mundo. _Avemaría_.

* *Cuarto Día*: Os saludamos, oh Elegida, que, cual sol sin mancha alguna, despuntasteis en la noche más tenebrosa del pecado. _Avemaría_.

* *Quinto Día*: Os saludamos, oh bellísima Luna, que iluminasteis al mundo envuelto en las más densas tinieblas del gentilismo. _Avemaría_.

* *Sexto Día*: Os saludamos como a esforzada amazona, que sola, a manera de un numeroso ejército, pusisteis en fuga a todo el infierno. _Avemaría_.

* *Séptimo Día*: Os saludamos, oh hermosa alma de María, a quien Dios poseyó desde la eternidad. _Avemaría_.

* *Octavo Día*: Os saludamos, oh amada Niña, y veneramos vuestro santísimo cuerpecito, los sagrados pañales en que fuisteis envuelta, y la sagrada cuna en que estuvisteis acostada, y bendecimos el punto y momento en que nacisteis. _Avemaría_.

* *Noveno Día*: Os saludamos finalmente, oh amada Niña, como adornada de todas las virtudes en grado inmensamente mas elevado que los otros Santos, y que, hecha digna Madre del Salvador, y habiendo concebido por virtud del Espíritu Santo, paristeis al Verbo encarnado. _Avemaría_.

*Oración final*

¡Oh graciosísima Niña! que con vuestro feliz nacimiento habéis consolado al mundo, alegrado al cielo y aterrado al infierno; habéis dado ayuda a los caídos, consuelo a los tristes, salud a los enfermos y alegría a todos; os suplicamos con los mas fervorosos afectos que renazcáis espiritualmente con vuestro santo amor en nuestras almas; renovad nuestro espíritu para que os sirvamos, encended de nuevo nuestro corazón para que os amemos; y haced florecer en nosotros aquellas virtudes con las que podamos hacernos siempre mas agradables a vuestros benignísimos ojos. ¡Oh María! Sed para nosotros María, haciéndonos experimentar los saludables efectos de vuestro suavísimo Nombre; sírvanos la invocación de este Nombre de alivio en los trabajos, de esperanza en los peligros, de escudo en las tentaciones, de aliento en la muerte. Sea el Nombre de María como la miel en la boca, la melodía en el oído, y el júbilo en el corazón. Así sea.