[[dolorosos]]
== Misterios Dolorosos (Martes y Viernes)

[[huerto]]
=== La Agonía de Nuestro Señor en el Huerto de los Olivos

Y llegan a una granja, cuyo nombre es Getsemaní, y dice a sus discípulos: «sentaos aquí mientras hago oración». Y lleva consigo a Pedro y a Santiago y a Juan, y comenzó a sentir espanto y abatimiento; y le dice: «triste en gran manera está mi corazón hasta la muerte; quedad aquí y velad». Y apartándose un poco, caía sobre tierra, y rogaba que, a ser posible, pasase el Él aquella hora, y decía: «Abba, Padre, todas las cosas te son posibles: traspasa de mi este cáliz; más no se haga lo que yo quiero, sino lo que tú». Y viene, y los halla durmiendo, y dice a Pedro: «¡Simón!¿Duermes?¿No pudiste velar una hora? Velad y orad para que no entréis en tentación; el espíritu, sí, está pronto, más la carne es flaca». Y luego, estando Él hablando todavía, se presenta Judas, uno de los Doce, y con él una turba con espadas y bastones, de parte de los escribas y los ancianos. Y así que llegó, luego acercándose dijo: «Rabí». Y le dió un fuerte beso. Ellos le echaron las manos y le sujetaron.Y abandonándole, huyeron todos. _Marcos 14,32-38.43.45-46.50_

1 Paternoster, 10 Avemarías, 1 Gloria y <<finalAgonia, ¡Oh Jesús mío!>>

***

1. *_Paternoster_* | Hijo, si te acercares a servir al Señor Dios, prepara tu alma a la tentación Gobierna tu corazón y muéstrate firme y no te apresures en tiempo de evasión. _Eci. 2,1-2_ | *_Ave María_*

2. Y llegan a una granja, cuyo nombre es Getsemaní, y dice a sus discípulos: «sentaos aquí mientras hago oración». Y lleva consigo a Pedro y a Santiago y a Juan, y comenzó a sentir espanto y abatimiento; y le dice: «triste en gran manera está mi corazón hasta la muerte; quedad aquí y velad». _Mc. 14,32-34_ | *_Ave María_*

3. Y apartándose un poco, caía sobre tierra, y rogaba que, a ser posible, pasase el Él aquella hora, y decía: «Abba, Padre, todas las cosas te son posibles: traspasa de mi este cáliz; más no se haga lo que yo quiero, sino lo que tú». _Mc. 14,35-36_ | *_Ave María_*

4. Y viene, y los halla durmiendo, y dice a Pedro: «¡Simón!¿Duermes?¿No pudiste velar una hora? Velad y orad para que no entréis en tentación; el espíritu , sí, está pronto, más la carne es flaca». _Mc. 14,37-38_ | *_Ave María_*

5. Y de nuevo habiéndse retirado se puso a orar, repitiendo las mismas palabras. Y volviendo los halló otra vez durmiendo, porque estaban sus ojos cargados, y no qué responderle. _Mc. 14,39-40_ | *_Ave María_*

6. Y viene tercera vez y les dice: «Ya por mi, dormid y descansad... Ya está: llegó la hora; he aquí que es entregado el Hijo del hombre en las manos de los pecadores. Levantaos, vamos; mirad, el que me entrega está aquí cerca». _Mc. 14,41-42_ | *_Ave María_*

7. Y luego, estando Él hablando todavía, se presenta Judas, uno de los Doce, y con él una turba con espadas y bastones, de parte de los escribas y los ancianos. Y así que llegó, luego acercándose dijo: «Rabí». Y le dió un fuerte beso. Ellos le echaron las manos y le sujetaron. _Mc. 14,43.45-46_ | *_Ave María_* 

8. En aquella hora dijo Jesús a las turbas: «¡cómo contra un salteador habéis salido con espadas y bastones a prenderme! Cada día en el templo me sentaba para enseñar, y no me predisteis. Mas todo esto ha pasado para que se cumplan las Escrituras de los profetas». Entonces los discípulo todos, abandonándole, huyeron». _Mt. 26, 55-56_ | *_Ave María_*

9. No volverá atrás la colerá de Yahveh hasta que ejecute y lleve a efecto los dedignios de su corazón; al fin de los tiempos adquiriréis de ello inteligencia. _Jer 23,20_ | *_Ave María_*

10. [Y Samuel exclamó:] «¿Acaso se complace Yahveh tanto en holocaustos y sacrificios cuanto en que se obedezca su voz? He aquí que la obediencia vale más que el sacrificio y la docilidad más que la grosura de carneros». _1 Sam 15,22_ | *_Ave María_* y *_Gloria_*

***

[[finalAgonia]]
include::ohjesus.adoc[]

[[flagelacion]]
=== La flagelación de Nuestro Señor Jesucristo

Y luego al amanecer, después de celebrar consejo, los sumos sacerdotes con los ancianos y los escribas, es decir, todo el sanhedrín, atando a Jesús, le llevaron de allí y le entregaron a Pilato. Y le interrogó Pilato: «¿Tú eres el Rey de los judíos?». El le respondió: «Tú lo dices». _Marcos 15, 1-2_

«Yo no hallo en Él delito alguno. Es costumbre vuestra que yo os suelte un preso por la Pascua: ¿queréis, pues, que os suelte al rey de los Judíos?». Gritaron, pues, de nuevo, diciendo: «No, a ése, sino a Barrabás». Era este Barrabás un salteador. Entonces, pues, tomó Pilato a Jesús y le azotó. _Juan 18,38-40;19,1_

1 Paternoster, 10 Avemarías, 1 Gloria y <<finalFlagelacion, ¡Oh Jesús mío!>>

***

1. *_Paternoster_* | Y luego al amanecer, después de celebrar consejo, los sumos sacerdotes con los ancianos y los escribas, es decir, todo el sanhedrín, atando a Jesús, le llevaron de allí y le entregaron a Pilato. Y le interrogó Pilato: «¿Tú eres el Rey de los judíos?». El le respondió: «Tú lo dices». _Mc. 15, 1-2_ | *_Ave María_*

2. Respondió Jesús: «Mi reino no es de este mundo. Si de este mundo fuera mi reino, mis ministros lucharían para que yo no fuera entregado a los judíos Más ahora mi reino no es de aquí». _Jn. 18, 36_ | *_Ave María_*

3. Díjole, pues, Pilato: «¿luego, rey eres tu?». Respondió Jesús: «Tú dices que yo soy rey. Yo para eso he nacido y para esto he venido al mundo: para dar testimonio a favor de la verdad. Todo el que es de la verdad, oye mi voz». _Jn. 18, 37_ | *_Ave María_*

4. Dícele Pilato: «¿Qué es verdad?». Dicho esto, de nuevo, salió a los judíos y les dice: «Yo no hallo en Él delito alguno. Es costumbre vuestra que yo os suelte un preso por la Pascua: ¿queréis, pues, que os suelte al rey de los Judíos?». Gritaron, pues, de nuevo, diciendo: «No, a ése, sino a Barrabás». Era este Barrabás un salteador. _Jn. 18, 38-40_ | *_Ave María_*

5. Entonces, pues, tomó Pilato a Jesús y le azotó. _Jn. 19, 1_ | *_Ave María_*

6. De opresión u juicio fué tomado, y a sus contemporáneos, ¿quién tendrá en cuenta?. Fué despreciado y abandonado de los hombres, varón de dolores y familiarizado de los hombres. _Is. 53, 8, 3_ | *_Ave María_*

7. Hízose para nosotros censura de nuestros criterios: pesado es para nosotros aun el verlo; pues discordante de los otros es su vida, y muy otros sus caminos. _Sab 2,14-15_ | *_Ave María_*

8. Fué traspasado por causa de nuestros pecados, molido por causa de nuestra iniquidades; el castigo [precio] de nuestra paz cayó sobre Él y por sus verdugones se nos curó; _Is. 53, 5_ | *_Ave María_*

9. ¡Oh vosotros kis que pasáis por el camino, mirad y ved si hay dolor semejante al dolor que me hiere, pues me ha afligido Yahveh en el día del ardor de su cólera! _Lm 1,12_ | *_Ave María_*

10. Yo soy el varón que ha visto la aflicción bajo el látigo de su cólera. Me ha guiado y conducido en tiniebla, sin luz; sólo contra mi vuelve y revuelve su mano todo el día. _Lm 3,1-3_ | *_Ave María_* y *_Gloria_*

***

[[finalFlagelacion]]
include::ohjesus.adoc[]

=== La coronación de espinas de Nuestro Señor Jesucristo {#espinas}

Entonces los soldados del gobernador, tomando a Jesús y conduciéndole al pretorio, reunieron en torno a Él toda la cohorte. Y habiéndole quitado sus vestidos, le envolvieron en una clámide de grana, y trenzando una corona de espinas, la pusieron sobre su cabeza, y una caña en su mano derecha; y doblando la rodilla delante de Él, le mofaban, diciendo: «Salud, Rey de los judíos». Y escupiendo en Él, tomaron la caña y le daban golpes en la cabeza. _Mateo 27, 27-30_

1 Paternoster, 10 Avemarías, 1 Gloria y <<finalEspinas, ¡Oh Jesús mío!>>

***

1. *_Paternoster_* | Del vestido miserable no te burles, ni te mofes de quien se halla en día aciago; porque maravillosas son las obras de Yahveh, y sus acciones son desconocidas de los hombres. _Eci 11,4_ | *_Ave María_*

2. Entonces los soldados del gobernador, tomando a Jesús y conduciéndole al pretorio, reunieron en torno a Él toda la cohorte. Y habiéndole quitado sus vestidos, le envolvieron en una clámide de grana. _Mt. 27, 28_ | *_Ave María_*

3. y trenzando una corna de espinas, la pusieron sobre la cabeza, y una caña en la mano derecha. _Mt. 27, 29_ | *_Ave María_*

4. y doblando la rodilla delante de Él, le mofaban, diciendo: «Salud, Rey de los judíos». _Mt. 27, 29_ | *_Ave María_*

5. Y escupiendo en Él, tomaron la caña y le daba golpes en la cabeza. _Mt 27, 30_ | *_Ave María_*

6. Hazte más pequeño cuanto más grande eres, y ante Dios hallarás gracia. _Eci 3,18_ | *_Ave María_*

7. ¡Cuántos se horrorizarán ante él, pues desfiguración sin aspeto humano ofrece su aspecto y su figura no es como la de los hiujos de los hombres! _Is 52,14_ | *_Ave María_*

8. Creció como un pimpollo delante de él, como raíz de tierra seca; no tiene apariencia ni belleza para que nos fijemos en él, ni aspecto para que en él nos complazcamos. _Is 53,2_ | *_Ave María_*

9. Fué despreciado y abandonado de los hombres, varón de dolores y familiarizado con el sufrimiento, y como una ante el cual se oculta el rostro, les despreciamos y no le estimamos. _Is 53,3_ | *_Ave María_*

10. Mas nuestros sufrimientos él los ha llevado, nuestros dolores él los cargo sobre sí, mientras nosotros le tuvimos por azotado, por herido de Dios y abatido. _Is 53,4_ | *_Ave María_* y *_Gloria_*

***

[[finalEspinas]]
include::ohjesus.adoc[]

[[cruz]]
=== Jesús con la Cruz a cuestas

Entonces, pues, se le entregó para que fuera crucificando. Se apoderaron, pues, de Jesús, y llevándo a cuestas su cruz, salió hacia el lugar llamado el Cráneo, que en hebreo se dice Gólgota. _Juan 19, 16-17_

1 Paternoster, 10 Avemarías, 1 Gloria y <<finalCruz, ¡Oh Jesús mío!>>

***

1. *_Paternoster_* | Fue maltratado, mas el se doblegó y no abre la boca; como cordero llevado al matadero y cual oveja ante sus esquiladores enmudecida, y no abre la boca. _Is 53,7_ | *_Ave María_*

2. Me han rodeado de un vallado y no puedo salir, me han aherrojado con pesadas cadena. Aunque grito y pido auxilio, ha cerrado el paso a mi plegaria. Ha obstruido mis caminos con piedras sillares, mis senderos han hecho instransitables. _Lm 3,7-9_ | *_Ave María_*

3. Al cuello tenemos los acosadores, estamos fatigados, no tenemos reposo. Los jovenes han tenido que arrastrar muela, y los muchachos han vacilado y caído, cargados de leña. _Lm 5,5.13_ | *_Ave María_*

4. Vagaron vacilantes como ciegos por las calles, manchados de sangre, sin que nadie pudiera tocar sus vestiduras. «¡Apartaos!¡Un impuro!, les gritaban. ¡Apartaos, apartaos!¡No toquéis!» Cuando huyieron y vagaron vacilantes, decíase entre las naciones: «¡no pueden quedarse [aquí]!». _Lm 4,14-15_ | *_Ave María_*

5. Si alguno quiere venir en pos de Mí, niégese a sí mismo y tome a cuestas su cruz cada día y sígame. _Lc. 9, 23_ | *_Ave María_*

6. Gritaron, pues, ellos: «Quita, quita, crucifícale». Díceles Pilato: «¿A vuestro rey voy he de crucificar?». Respondieron los pontífices: «No tenemos rey, sino César». Entonces, pues, se le entregó para que fuera crucificando. Se apoderaron, pues, de Jesús. _Jn. 19, 15-16_ | *_Ave María_*

7. Y, llevando a cuestas su cruz, salió hacia el lugar llamado el Cráneo, que en hebreo se dice Gólgota. _Jn. 19, 17_ | *_Ave María_*

8. Y como le hubieron sacado, echaron mano de un tal Simón de Cirene que venía del campo, le pusieron en hombros la cruz para que la llevase detrás de Jesús. _Lc. 23, 26_ | *_Ave María_*

9. Tomad mi yugo sobre vuestros, y aprended de mi, pues soy manso y humilde de Corazón, y hallaréis reposo para vuestras almas. _Mt. 11, 29_ | *_Ave María_*

10. Porque mi yugo es suave, y mi carga, ligera. _Mt. 11, 30_  | *_Ave María_* y *_Gloria_*

***

[[finalCruz]]
include::ohjesus.adoc[]

[[muerte]]
=== La Crucifixión y Muerte del Redentor

Y cuando hubieron llegado al lugar llamado «Cráneo», allí crucificaron a Él y a los malhechores, uno a la derecha y otro a la izquierda. Y Jesús decía: «Padre, perdónales porque no saben lo que hacen». Y al repartir sus vestidos, echaron suertes. Había también por encima de Él una inscripción escrita en letras griegas, latinas y hebreas: ESTE ES EL REY DE LOS JUDIOS. Y clamando con voz poderosa, Jesús dijo: «Padre, en tus manos encomiendo mi espíritu». Y dicho esto, expiró. _Lucas 23, 33-34.38.46_

1 Paternoster, 10 Avemarías, 1 Gloria y <<finalCrucifixion, ¡Oh Jesús mío!>>

***

1. *_Paternoster_* | Y respondió Abraham: «Dios proveerá de cordero para el holocausto, hijo mío». _Gn. 22, 8_ | *_Ave María_*

2. Y cuando hubieron llegado al lugar llamado «Cráneo», allí crucificaron a Él y a los malhechores, uno a la derecha y el otro a la izquierda. Y Jesús decía: «Padre, perdónalos, porque no saben lo que hacen». Y al repartir sus vestidos, echaron suertes. _Lc. 23, 33-34_ | *_Ave María_*

3. Había también por encima de Él una inscripción escrita en letras griegas, latinas y hebreas: ESTE ES EL REY DE LOS JUDIOS. _Lc. 23, 38_ | *_Ave María_*

4. Uno de los malhechores que estaba colgado decía a Jesús: «acuérdate de mi cuando vinieres en la gloria de tu realeza». Díjole: «en verdad te digo que hoy estarás conmigo en el paraíso». _Lc. 23, 39, 42-43_ | *_Ave María_*

5. Jesús, pues, viendo a la Madre, y junto a ella al discípulo a quien amaba, dice a tu Madre: «Mujer, he ahí a tu hijo». Luego dice al discípulo: «He aquí a tu Madre». Y desde aquella hora la tomó el discípulo en su compañía. _Jn. 19, 26-27_ | *_Ave María_*

6. Y era ya como la hora sexta, y se produjeron tinieblas sobre toda la tierra hasta la hora nona, habiendo faltado el sol; y se rasgó por medio el velo del santuario. _Lc. 23, 44-45_ | *_Ave María_*

7. Y clamando con voz poderosa, Jesús dijo: «Padre, en tus manos encomiendo mis espíritu». (Lc. 23, 46) [Jesús dijo:] «Consumado está». E inclinando la cabeza entregó el espíritu. _Jn. 19, 30_ | *_Ave María_*

8. Y vi en medio delante del trono y de los cuatro vivientes, y en medio de los ancianos, un Cordero de pié, como degollado, que tenía siete cuernos y siete ojos, que son los siete Espíritus de Dios, enviados por toda la tierra. _Ap 5,6_ | *_Ave María_*

9. Mas viendo a Jesús, cuando vinieron, como le vieron ya muerto, no le quebrantaron las piernas, sino que uno de los soldados con una lanza le traspasó el costado, y salió al punto sangre y agua. _Jn 19,33-34_ | *_Ave María_*

10. Y me mostró un río de agua de vida, luciente como cristal, que salía del Trono de Dios y del Cordero. _Ap 22,1_ | *_Ave María_* y *_Gloria_*

***

[[finalCrucifixion]]
include::ohjesus.adoc[]

<<confiteor, Confíteor>>
