[[letanias]]
==== Letanías lauretanas

Señor, ten piedad. +
_Kýrie, eléison._

Señor, ten piedad. +
_Kýrie, eléison._

Cristo, ten piedad. +
_Christe, eléison._

Cristo, ten piedad. +
_Christe, eléison._

Señor, ten piedad. +
_Kýrie, eléison._

Señor, ten piedad. +
_Kýrie, eléison._

Cristo, óyenos. +
_Christe, audi nos._

Cristo, óyenos. +
_Christe, audi nos._

Cristo, escúchanos. +
_Christe, exáudi nos._

Cristo, escúchanos. +
_Christe, exáudi nos._

Dios, Padre celestial, tened misericordia de nosotros. +
_Pater de cælis, Deus, miserére nobis._

Dios Hijo, Redentor del mundo, tened misericordia de nosotros. +
_Fili, Redémptor mundi, Deus, miserére nobis._

Dios Espíritu Santo, tened misericordia de nosotros. +
_Spíritus Sancte, Deus, miserére nobis._

Trinidad Santa, un solo Dios, tened misericordia de nosotros. +
_Sancta Trínitas, unus Deus, miserére nobis._

Santa María, rogad por nosotros. +
_Sancta Maria, ora pro nobis._

Santa Madre de Dios, rogad por nosotros. +
_Sancta Dei Génetrix, ora pro nobis._

Santa Virgen de las vírgenes, rogad por nosotros. +
_Sancta Virgo vírginum, ora pro nobis._

Madre de Cristo, rogad por nosotros. +
_Mater Christi, ora pro nobis._

Madre de la Iglesia, rogad por nosotros. +
_Mater Ecclésiæ, ora pro nobis._

Madre de la divina gracia, rogad por nosotros. +
_Mater divínæ gratiæ, ora pro nobis._

Madre purísima, rogad por nosotros. +
_Mater puríssima, ora pro nobis._

Madre castísima, rogad por nosotros. +
_Mater castíssima, ora pro nobis._

Madre virginal, rogad por nosotros. +
_Mater invioláta, ora pro nobis._

Madre sin corrupción, rogad por nosotros. +
_Mater intemeráta, ora pro nobis._

Madre inmaculada, rogad por nosotros. +
_Mater immaculáta, ora pro nobis._

Madre amable, rogad por nosotros. +
_Mater amábilis, ora pro nobis._

Madre admirable, rogad por nosotros. +
_Mater admirábilis, ora pro nobis._

Madre del Buen Consejo, rogad por nosotros. +
_Mater boni Consílii, ora pro nobis._

Madre del Creador, rogad por nosotros. +
_Mater Creatóris, ora pro nobis._

Madre del Salvador, rogad por nosotros. +
_Mater Salvatóris, ora pro nobis._

Virgen pru­den­tísima, rogad por nosotros. +
_Virgo pru­den­tíssima, ora pro nobis._

Virgen digna de veneración, rogad por nosotros. +
_Virgo veneránda, ora pro nobis._

Virgen digna de alabanza, rogad por nosotros. +
_Virgo prædicánda, ora pro nobis._

Virgen poderosa, rogad por nosotros. +
_Virgo potens, ora pro nobis._

Virgen clemente, rogad por nosotros. +
_Virgo clemens, ora pro nobis._

Virgen fiel, rogad por nosotros. +
_Virgo fidélis, ora pro nobis._

Espejo de justicia, rogad por nosotros. +
_Spéculum iustítiæ, ora pro nobis._

Trono de sabiduría, rogad por nosotros. +
_Sedes Sapiéntiæ, ora pro nobis._

Causa de nuestra alegría, rogad por nosotros. +
_Causa nostræ lætítiæ, ora pro nobis._

Vaso espiritual, rogad por nosotros. +
_Vas spirituále, ora pro nobis._

Vaso digno de honor, rogad por nosotros. +
_Vas honorábile, ora pro nobis._

Vaso insigne de devoción, rogad por nosotros. +
_Vas insigne devotiónis, ora pro nobis._

Rosa mística, rogad por nosotros. +
_Rosa mýstica, ora pro nobis._

Torre de David, rogad por nosotros. +
_Turris Davídica, ora pro nobis._

Torre de marfil, rogad por nosotros. +
_Turris ebúrnea, ora pro nobis._

Casa de oro, rogad por nosotros. +
_Domus áurea, ora pro nobis._

Arca de la alianza, rogad por nosotros. +
_Fœderis arca, ora pro nobis._

Puerta del cielo, rogad por nosotros. +
_Iánua cæli, ora pro nobis._

Estrella de la mañana, rogad por nosotros. +
_Stella matutina, ora pro nobis._

Salud de los enfermos, rogad por nosotros. +
_Salus infirmórum, ora pro nobis._

Refugio de los pecadores, rogad por nosotros. +
_Refugium peccatórum, ora pro nobis._

Consuelo de los afligidos, rogad por nosotros. +
_Consolátrix af­flic­tórum, ora pro nobis._

Auxilio de los cristianos, rogad por nosotros. +
_Auxílium chris­tia­nórum, ora pro nobis._

Reina de los Ángeles, rogad por nosotros. +
_Regina Angelórum, ora pro nobis._

Reina de los Patriarcas, rogad por nosotros. +
_Regina Pa­triar­chárum, ora pro nobis._

Reina de los Profetas, rogad por nosotros. +
_Regina Pro­phe­tárum, ora pro nobis._

Reina de los Apóstoles, rogad por nosotros. +
_Regina Apos­to­lórum, ora pro nobis._

Reina de los Mártires, rogad por nosotros. +
_Regina Mártyrum, ora pro nobis._

Reina de los Confesores, rogad por nosotros. +
_Regina Con­fe­ssórum, ora pro nobis._

Reina de las Vírgenes, rogad por nosotros. +
_Regina Vírginum, ora pro nobis._

Reina de todos los Santos, rogad por nosotros. +
_Regina Sanctórum ómnium, ora pro nobis._

Reina concebida sin pecado original, rogad por nosotros. +
_Regina sine labe originali concépta, ora pro nobis._

Reina elevada al cielo, rogad por nosotros. +
_Regina in cælum assumpta, ora pro nobis._

Reina del Santísimo Rosario, rogad por nosotros. +
_Regina sa­cra­tíssimi Rosárii, ora pro nobis._

Reina de la familia, rogad por nosotros. +
_Regina famíliæ, ora pro nobis._

Reina de la paz, rogad por nosotros. +
_Regina pacis, ora pro nobis._

Cordero de Dios, que quitas los pecados del mundo, perdonadnos, Señor. +
_Agnus Dei, qui tollis peccáta mundi,_ _parce nobis, Dómine._

Cordero de Dios, que quitas los pecados del mundo, escuchadnos, Señor. +
_Agnus Dei, qui tollis peccáta mundi,_ _exáudi nos, Dómine._

Cordero de Dios, que quitas los pecados del mundo, tened piedad de nosotros+
_Agnus Dei, qui tollis peccáta mundi, miserére nobis._

Bajo tu amparo nos acogemos, Santa Madre de Dios: no desprecies las súplicas que te dirigimos en nuestras necesidades, antes bien, líbranos siempre de todos los peligros, Virgen gloriosa y bendita. +
_Sub tuum præsídium confúgimus, Sancta Dei Génetrix, nostras de­pre­ca­tiónes ne despícias in ne­ces­si­tátibus; sed a perículis cunctis líbera nos semper, Virgo gloriósa et benedícta._

Ruega por nosotros, Santa Madre de Dios. Para que seamos dignos de alcanzar las promesas de nuestro Señor Jesucristo. +
_Ora pro nobis, Sancta Dei Génetrix. Ut digni efficiámur pro­mi­ssiónibus Christi._