[[salve-regina]]
=== Salve, Regina

Dios te salve, Reina y Madre de mi­se­ri­cordia, vida, dulzura y esperanza nuestra; Dios te salve. A ti llamamos los desterrados hijos de Eva; a ti suspiramos, gimiendo y llorando en este valle de lágrimas. Ea, pues, Señora, abogada nuestra, vuelve a nosotros esos tus ojos mi­se­ri­cordiosos. Y después de este destierro, muéstranos a Jesús, fruto bendito de tu vientre. ¡Oh cle­men­tísima, oh piadosa, oh dulce siempre Virgen María! +
V/ Ruega por nosotros, Santa Madre de Dios. +
R/ Para que seamos dignos de alcanzar las promesas de nuestro Señor Jesucristo.

_Salve, Regina, Mater mi­se­ri­córdiæ, vita, dulcédo et spes nostra, salve. Ad te clamámus, éxsules fílii Hevæ. Ad te suspirámus geméntes et flentes in hac lacrimárum valle. Éia ergo, advocáta nostra, illos tuos mi­se­ri­córdes óculos ad nos convérte. Et Iesum benedíctum fructum ventris tui, nobis,post hoc exsílium, osténde. O clemens, o pia, o dulcis Virgo Maria!_ +
_V/ Ora pro nobis, Sancta Dei Génetrix._ +
_R/ Ut digni efficiámur pro­mi­ssiónibus Christi._
